language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install: pip install -r requirements.txt --use-mirrors
script: 
  - flake8 file_syncer/

notifications:
  email:
    - tomaz+travisci@tomaz.me
